[package]
name = "test-rs"
version = "0.1.0"
authors = ["Vegard Sandengen <vegardsandengen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
testcontainers = "0.12"
dockertest = "0.2"
