on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install zola'
        run: |
          wget -q -O - \
          "https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz" \
          | sudo tar xzf - -C /usr/local/bin

      - name: 'Build'
        run: zola build

      - name: 'Push'
        run: |
          cd public
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .

          git commit -m "Automatic deploy"
          git push --force "https://${{ secrets.TOKEN }}@github.com/veeg/blog.git" master:gh-pages
